server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /chargement/ {
        proxy_pass http://backend:8000/chargement/;
    }

    location /visualisation/ {
        proxy_pass http://backend:8000/visualisation/;
    }

    location /analyse/ {
        proxy_pass http://backend:8000/analyse/;
    }
}